baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "sam"
[params]
	homepage = "main"

[[params.mainMenu]]
	link = "gallery"
	text = "gallery"

[[params.mainMenu]]
	link = "about"
	text = "about"
