baseURL = "https://isaiah-test.netlify.app/"
languageCode = "en-us"
title = "ODON"

theme = "sam"
[params]
	homepage = "main"

[[params.mainMenu]]
	link = "gallery"
	text = "gallery"

[[params.mainMenu]]
	link = "about"
	text = "about"
